[printer T300]
moonraker_host: 127.0.0.1
moonraker_port: 7125

[main]
default_printer: T300
theme: material-light
use_default_menu: False
confirm_estop: False
use_dpms: True
screen_blanking: 900
show_cursor: False
job_complete_timeout: 0
job_error_timeout: 0

[menu __main]
name: T300

[menu __main print_workflow]
name: Print
icon: printer

[menu __main print_workflow plate_ready]
name: Clean & Rearm Plate
icon: complete
method: printer.gcode.script
params: {"script":"BUILD_PLATE_READY"}

[menu __main print_workflow select_file]
name: Select Print File
icon: files
panel: gcodes

[menu __main home_printer]
name: Home Printer
icon: home
method: printer.gcode.script
params: {"script":"HOME_PRINTER"}

[menu __main camera]
name: Camera
icon: camera
panel: camera
enable: {{ moonraker.cameras.count > 0 }}

[menu __main notifications]
name: Notifications
icon: notifications
panel: notifications

[menu __print]
name: Print Status

[menu __print camera]
name: Camera
icon: camera
panel: camera
enable: {{ moonraker.cameras.count > 0 }}

[menu __print notifications]
name: Notifications
icon: notifications
panel: notifications
